version: '3'

services:
  postgres:
    image: postgres:13.1
    container_name: telhabot-postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=star
      - APP_DB_PASS=wader
      - APP_DB_NAME=habot
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
